# -*- coding: utf-8 -*-

{
    "name": "Two Factor Authentication",
    "version": "1.0",
    "author": "",
    "category": "Security",
    "website": "",
    "description": """
Two Factor Authentication
This module uses TOTP generated by google authenticator, to authenticate a user in Odoo.
      """,
    "depends": ["base", "web", "email_template"],
    "init_xml": [],
    "data": ["res_users.xml", "static/src/xml/base.xml", "static/src/xml/two_factor.xml"],
    "active": True,
    "installable": True
}
